title: UniSim3Doc
description: Universal Simulator documentation
theme: just-the-docs

url: https://NielsHolst.github.io/UniSim3Doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# include:
  # - virtual-greenhouse.md
  # - models/virtual-greenhouse.md
  # - models/vg.md
  
exclude:
  - illustrations/
  - src/
  - Gemfile
  - Gemfile.lock
