title: UniSim3Doc
description: Universal Simulator documentation
theme: just-the-docs

url: https://NielsHolst.github.io/UniSim3Doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

exclude:
  - doc/
  - doc-md/
  - lab/
  - lab-md/
  - media-ppt/
  - models-src/
  - old/
  - process/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - index.html
